### PR TITLE
Example of Pull Request

### PR DESCRIPTION
**Pull request by MasterOfTheTiger**
This is an example of a pull request. I am not sure how much you know about this, but I will explain what I did.

1. Fork
I forked it and made my own copy of your repository.
2. Edit
I then edited the repository and made a new file.
3. Pull request
I made a pull request that basically is a request for my changes to be merged into your repository. That is very useful for open source projects.

### CODE REVIEW

**Comment by MasterOfTheTiger** [comment]
Hey @hellounicorns2 did you even see this?

**Comment by hellounicorns2** [comment]
Ayyy only jus noticed it for some reason I misplaced the original email. I’ll merge the pull request. Anyways, thanks for helping out!

**Comment by hellounicorns2** [comment]
Btw I didn’t know what pull requests were! 😀

**Comment by MasterOfTheTiger** [comment]
@hellounicorns2 This pull request is just a simple thing for me to show you how it works. I did not understand pull requests for a while after I started using GitHub. 

@hellounicorns2 yep you can edit posts.

**Comment by hellounicorns2** [comment]
Cool. Now can I test locking this?

**Comment by hellounicorns2** [comment]
Oh only collaborators can comment when locked ah see :P

**Comment by hellounicorns2** [comment]
Thanks for helping.

I’m learning HTML, cya!

**Pull request merged**
